# Default values for cockroachdbchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: cockroachdb/cockroach:v19.2.0

siteName: "roach"
storageSize: "50Gi"

postgresqlPort: 26257
webUiPort: 8080

